### ISSUE TITLE
Add options to test

### ISSUE THREAD

**Issue by lorenzoPrimi** [measurement-kit/measurement-kit-android#11]
I'm implementing the settings in the Android app, I need a way to add various options to tests like "collector_base_url", "save_real_probe_ip" and "save_real_probe_asn", so I guess it's better to start thinking a way that doesn't need to update the -android repo every time I need to add a different options.
Maybe sending an array of key/value options?

Example options sent in the iOS app:

    mk::ooni::HttpInvalidRequestLine()
        .set_options("backend", "http://213.138.109.232/")
        .set_options("dns/nameserver", get_dns_server())
        .set_options("net/ca_bundle_path", [ca_cert UTF8String])
        .set_options("geoip_country_path", [geoip_country UTF8String])
        .set_options("geoip_asn_path", [geoip_asn UTF8String])
        .set_options("save_real_probe_ip", include_ip)
        .set_options("save_real_probe_asn", include_asn)
        .set_options("collector_base_url", [collector_address UTF8String])

**Comment by bassosimone** [comment]
Wouldn't be enough to expose the `set_options(string, string)` function?

**Comment by lorenzoPrimi** [comment]
exactly what I needed 👍

**Comment by bassosimone** [comment]
Closing because this was implemented in #13
