### ISSUE TITLE
Find alternative to always copying resources

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit-android#17]
As pointed out by @AntonioLangiu in [#16](https://github.com/measurement-kit/measurement-kit-android/pull/16#discussion_r84598842):

> I don't actually like the fact that we need to copy the file every time we start the app. It's just 4 mb, not too much, but maybe we can find a better solution.

This issue is here to track ways to do that. (I don't think this is high priority, tho.)

**Comment by lorenzoPrimi** [comment]
Fixed in https://github.com/measurement-kit/ooniprobe-android/commit/5c085cca572e69800545e646fee42200313e8e2f

**Comment by lorenzoPrimi** [comment]
@bassosimone @AntonioLangiu check it

**Comment by AntonioLangiu** [comment]
You have to consider the fact that when we update the application we may want to update also this assets.

I remember that `SharedPreferences` are persistent to App updates and so you will always have  [the `"resource_copied"` value setted to true](https://github.com/measurement-kit/ooniprobe-android/commit/5c085cca572e69800545e646fee42200313e8e2f#diff-f6b2e95d7124a275fc3b63f68fab2036R135).

A good solution for this could be to store in the SharedPreferences also an `App version` field and check if the current running version is different from the stored one.

**Comment by lorenzoPrimi** [comment]
As there will not be many updates of the app for now, we can also change the "resource_copied" value in "resource_copied_1" only if an asset has changed

**Comment by AntonioLangiu** [comment]
Yes, why not :) we just need to remember somehow this fact for the next release! 👍

**Comment by bassosimone** [comment]
Assets are: CA certificates lists; input lists; GeoIP files. Of those, only CA certificates are needed at the beginning for bootstrapping the app and all the rest should be downloaded by us.

Just a reminder.
